# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-image: url(D:/python/CNN/1.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trainButton = QtWidgets.QPushButton(self.centralwidget)
        self.trainButton.setGeometry(QtCore.QRect(110, 290, 141, 61))
        self.trainButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #5c5c5c;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.trainButton.setObjectName("trainButton")
        self.recognizeButton = QtWidgets.QPushButton(self.centralwidget)
        self.recognizeButton.setGeometry(QtCore.QRect(410, 290, 141, 61))
        self.recognizeButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #5c5c5c;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.recognizeButton.setObjectName("recognizeButton")
        self.captureButton = QtWidgets.QPushButton(self.centralwidget)
        self.captureButton.setGeometry(QtCore.QRect(710, 290, 141, 61))
        self.captureButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #5c5c5c;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.captureButton.setObjectName("captureButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(80, 70, 841, 71))
        self.textBrowser.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #5c5c5c;\n"
"    color: #000;\n"
"}\n"
"")
        self.textBrowser.setObjectName("textBrowser")
        self.captureButton.raise_()
        self.recognizeButton.raise_()
        self.trainButton.raise_()
        self.textBrowser.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        self.menuface = QtWidgets.QMenu(self.menubar)
        self.menuface.setObjectName("menuface")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuface.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.trainButton.setText(_translate("MainWindow", "Train Model"))
        self.recognizeButton.setText(_translate("MainWindow", "Recognize Faces"))
        self.captureButton.setText(_translate("MainWindow", "Capture Faces"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:24pt; color:#ffffff;\">Face recognition system based on cnn</span></p></body></html>"))
        self.menuface.setTitle(_translate("MainWindow", "face"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
